export const governanceComparisonCopy = Object.freeze({
  zh: Object.freeze({
    pageTitle: '政策对比分析',
    pageDescription:
      '以所选政策所属国家为入口，对现行治理体系、项目落地和关键监管机制进行横向分析。',
    clear: '清空选择',
    export: '导出分析报告 (PDF)',
    reportTitle: 'CCUS 政策对比分析简报',
    generated: '生成日期',
    capabilityEyebrow: '治理体系对标',
    capabilityTitle: '治理能力画像',
    capabilitySubtitle: '峰值政策强度',
    scopeTitle: '分析范围',
    scopeNote: '默认比较所选政策所属国家的全部现行政策体系。',
    scopeSystem: '国家现行政策体系',
    scopeSelected: '仅所选现行政策',
    matrixTitle: '治理—部署矩阵',
    matrixSubtitle: '治理能力 × 已承诺项目规模',
    benchmarkPrefix: '全球基准',
    benchmarkGovernanceLabel: '治理基准',
    benchmarkDeploymentLabel: '部署基准',
    benchmarkGovernance: '治理能力指数中位数',
    benchmarkDeployment: '有已承诺项目国家的项目记录规模中位数',
    benchmarkMethod: '治理能力指数为五个峰值维度的平均值。',
    qPolicy: '制度先行',
    qLeader: '协同领先',
    qFoundation: '基础培育',
    qDeployment: '工程先行',
    facilityTitle: '设施规模对标',
    facilityNote: '矩阵部署规模仅包括在运与在建设施；规划规模不计入横轴。',
    evidenceEyebrow: '证据与来源',
    contributors: '治理核心贡献政策',
    regulatory: '关键制度要素对标',
    emptyTitle: '暂未选择对比政策',
    emptyDescription:
      '请从政策数据库中选择多项政策（最多 5 项），再进入国家治理能力与项目落地对比。',
    emptyAction: '前往政策数据库',
    emptyHref: '/ccus-policy-hub/policy/',
  }),
  en: Object.freeze({
    pageTitle: 'Policy Comparison Analysis',
    pageDescription:
      'Use selected policies as entry points to compare active national governance systems, project deployment and critical regulatory mechanisms.',
    clear: 'Clear all',
    export: 'Export report (PDF)',
    reportTitle: 'CCUS Policy Comparison Brief',
    generated: 'Generated',
    capabilityEyebrow: 'Governance Capability Profile',
    capabilityTitle: 'Governance Capability Profile',
    capabilitySubtitle: 'Peak Policy Strength',
    scopeTitle: 'Analysis scope',
    scopeNote:
      'The default view benchmarks the active national policy systems behind the selected policies.',
    scopeSystem: 'Active national policy system',
    scopeSelected: 'Selected active policies only',
    matrixTitle: 'Governance–Deployment Matrix',
    matrixSubtitle:
      'Governance capability versus committed project-record scale',
    benchmarkPrefix: 'Global benchmark',
    benchmarkGovernanceLabel: 'Governance benchmark',
    benchmarkDeploymentLabel: 'Deployment benchmark',
    benchmarkGovernance: 'median governance capability',
    benchmarkDeployment:
      'median committed project-record scale among countries with committed projects',
    benchmarkMethod:
      'The governance capability index is the mean of five peak dimensions.',
    qPolicy: 'Policy-led',
    qLeader: 'Integrated leaders',
    qFoundation: 'Foundation building',
    qDeployment: 'Deployment-led',
    facilityTitle: 'Facility benchmarking',
    facilityNote:
      'The matrix deployment scale includes operational and under-construction facilities only; planned scale is excluded from the x-axis.',
    evidenceEyebrow: 'Evidence & provenance',
    contributors: 'Governance peak contributors',
    regulatory: 'Critical regulatory benchmarking',
    emptyTitle: 'No policies selected',
    emptyDescription:
      'Select up to five policies from the database to compare national governance capability and project deployment.',
    emptyAction: 'Go to policy database',
    emptyHref: '/ccus-policy-hub/en/policy/',
  }),
});
